spring:
   profiles:
      active: dev
---
# default servlet handler
# server:
#   error:
#      path: /ERROR
# default servelt handler 사용 시 에러 터졌을 때 특정 path로 보내지는데 default값으로 얻는 값으로 가게끔 /error로 !!

spring:
   resources:
      add-mappings: false
   mvc:
      throw-exception-if-no-handler-found: false
      
---
# common : spring boot configuration
spring:
   # devtools 설정 - live reload
   livereload:
      enabled: true
      
   # mvc 설정
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
   # message resource(Internationalization)
   messages:
      always-message-format: true
      basename: messages/messages_ko
      encoding: UTF-8
      
   #multipart
   multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

   #aop(@EnableAspectJAutoProxy)
   aop:
      auto: true
      proxy-target-class: true
---
# dev profile : spring boot configuration
spring:
   config:
      activate:
         on-profile: dev
   # data source
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.0.68:3307/jblog?characterEncoding=UTF-8&serverTimezone=UTC
      username: jblog
      password: jblog
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
---
# production profile : spring boot configuration
spring:
   config:
      activate:
         on-profile: production
   
   # data source 
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://211.45.3.5:3307/jblog?characterEncoding=UTF-8&serverTimezone=UTC
      username: jblog
      password: jblog@dfidjfaid
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

---
# server 
server:
   port: 8080
   servlet:
      context-path: /jblog06
      encoding:
         charset: utf-8
         enabled: true
         forced: false
         forced-request: false
         forced-response: false
     
---
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml
   
---
# logging 
logging:
   config: classpath:logback.xml